# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='list',
        ),
    ]
