# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20180713_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='text',
        ),
    ]
